/*
 *  This file is a part of MATCL-SIMD Library
 *
 *  Copyright (c) Pawel Kowal 2017 - 2023
 *
 *  This file is distributed under the BSD License. See LICENSE.txt for details.
 */

#pragma once

#ifdef MATCL_TEST_SIMD_FMA
    #define MATCL_ARCHITECTURE_HAS_SSE2 1
    #define MATCL_ARCHITECTURE_HAS_SSE3 1
    #define MATCL_ARCHITECTURE_HAS_SSE41 1
    #define MATCL_ARCHITECTURE_HAS_SSE42 1
    #define MATCL_ARCHITECTURE_HAS_AVX 1
    #define MATCL_ARCHITECTURE_HAS_AVX2 1
    #define MATCL_ARCHITECTURE_HAS_FMA 1

    #define MATCL_TEST_SIMD_TAG "fma"

#elif defined MATCL_TEST_SIMD_AVX2
    #define MATCL_ARCHITECTURE_HAS_SSE2 1
    #define MATCL_ARCHITECTURE_HAS_SSE3 1
    #define MATCL_ARCHITECTURE_HAS_SSE41 1
    #define MATCL_ARCHITECTURE_HAS_SSE42 1
    #define MATCL_ARCHITECTURE_HAS_AVX 1
    #define MATCL_ARCHITECTURE_HAS_AVX2 1
    #define MATCL_ARCHITECTURE_HAS_FMA 0

    #define MATCL_TEST_SIMD_TAG "avx2"

#elif defined MATCL_TEST_SIMD_AVX
    #define MATCL_ARCHITECTURE_HAS_SSE2 1
    #define MATCL_ARCHITECTURE_HAS_SSE3 1
    #define MATCL_ARCHITECTURE_HAS_SSE41 1
    #define MATCL_ARCHITECTURE_HAS_SSE42 1
    #define MATCL_ARCHITECTURE_HAS_AVX 1
    #define MATCL_ARCHITECTURE_HAS_AVX2 0
    #define MATCL_ARCHITECTURE_HAS_FMA 0

    #define MATCL_TEST_SIMD_TAG "avx"

#elif defined MATCL_TEST_SIMD_NO_SSE42
    #define MATCL_ARCHITECTURE_HAS_SSE2 1
    #define MATCL_ARCHITECTURE_HAS_SSE3 1
    #define MATCL_ARCHITECTURE_HAS_SSE41 1
    #define MATCL_ARCHITECTURE_HAS_SSE42 0
    #define MATCL_ARCHITECTURE_HAS_AVX 0
    #define MATCL_ARCHITECTURE_HAS_AVX2 0
    #define MATCL_ARCHITECTURE_HAS_FMA 0

    #define MATCL_TEST_SIMD_TAG "no_sse42"

#elif defined MATCL_TEST_SIMD_NO_SSE41
    #define MATCL_ARCHITECTURE_HAS_SSE2 1
    #define MATCL_ARCHITECTURE_HAS_SSE3 1
    #define MATCL_ARCHITECTURE_HAS_SSE41 0
    #define MATCL_ARCHITECTURE_HAS_SSE42 0
    #define MATCL_ARCHITECTURE_HAS_AVX 0
    #define MATCL_ARCHITECTURE_HAS_AVX2 0
    #define MATCL_ARCHITECTURE_HAS_FMA 0

    #define MATCL_TEST_SIMD_TAG "no_sse41"

#elif defined MATCL_TEST_SIMD_NO_SSE3
    #define MATCL_ARCHITECTURE_HAS_SSE2 1
    #define MATCL_ARCHITECTURE_HAS_SSE3 0
    #define MATCL_ARCHITECTURE_HAS_SSE41 0
    #define MATCL_ARCHITECTURE_HAS_SSE42 0
    #define MATCL_ARCHITECTURE_HAS_AVX 0
    #define MATCL_ARCHITECTURE_HAS_AVX2 0
    #define MATCL_ARCHITECTURE_HAS_FMA 0

    #define MATCL_TEST_SIMD_TAG "no_sse3"

#elif defined MATCL_TEST_SIMD_DEFAULT

    #define MATCL_TEST_SIMD_TAG "default"

#else
    #error unknown simd type
#endif